pick_race: true # If true, the player will be forced to pick a race on joining. If false, their race will have to be determined through commands
pick_class: true # If true, the player will be forced to pick a class on joining. If false, their class will have to be determined through commands

on_join: false # If true, and if pick_race or pick_class are enabled, players will pick their class or race when they join the server.
# IF FALSE, they get to pick when they first start moving instead.

confirm_message_race: '&cYou are now a %race%!'
confirm_message_class: '&cYou are now %class%!'

menus:
  races_slots: 45
  races_title: '&7Pick Your Race'
  races_decoration: # For decoration you may add ;<number> to any of these entries to determine their custom model data
    0: GRAY_STAINED_GLASS_PANE
    1: GRAY_STAINED_GLASS_PANE
    2: GRAY_STAINED_GLASS_PANE
    3: GRAY_STAINED_GLASS_PANE
    4: GRAY_STAINED_GLASS_PANE
    5: GRAY_STAINED_GLASS_PANE
    6: GRAY_STAINED_GLASS_PANE
    7: GRAY_STAINED_GLASS_PANE
    8: GRAY_STAINED_GLASS_PANE
    36: GRAY_STAINED_GLASS_PANE
    37: GRAY_STAINED_GLASS_PANE
    38: GRAY_STAINED_GLASS_PANE
    39: GRAY_STAINED_GLASS_PANE
    40: GRAY_STAINED_GLASS_PANE
    41: GRAY_STAINED_GLASS_PANE
    42: GRAY_STAINED_GLASS_PANE
    43: GRAY_STAINED_GLASS_PANE
    44: GRAY_STAINED_GLASS_PANE
  classes_slots: 45
  classes_title: '&7Pick Your Class'
  classes_decoration:
    0: GRAY_STAINED_GLASS_PANE
    1: GRAY_STAINED_GLASS_PANE
    2: GRAY_STAINED_GLASS_PANE
    3: GRAY_STAINED_GLASS_PANE
    4: GRAY_STAINED_GLASS_PANE
    5: GRAY_STAINED_GLASS_PANE
    6: GRAY_STAINED_GLASS_PANE
    7: GRAY_STAINED_GLASS_PANE
    8: GRAY_STAINED_GLASS_PANE
    36: GRAY_STAINED_GLASS_PANE
    37: GRAY_STAINED_GLASS_PANE
    38: GRAY_STAINED_GLASS_PANE
    39: GRAY_STAINED_GLASS_PANE
    40: GRAY_STAINED_GLASS_PANE
    41: GRAY_STAINED_GLASS_PANE
    42: GRAY_STAINED_GLASS_PANE
    43: GRAY_STAINED_GLASS_PANE
    44: GRAY_STAINED_GLASS_PANE

# Stats list
# GLOBAL_EXP_GAIN

# ARMOR_TOTAL
# TOTAL_LIGHT_ARMOR
# LIGHT_ARMOR
# LIGHT_ARMOR_MULTIPLIER
# TOTAL_HEAVY_ARMOR
# HEAVY_ARMOR
# HEAVY_ARMOR_MULTIPLIER
# TOTAL_WEIGHTLESS_ARMOR
# WEIGHTLESS_ARMOR
# ARMOR_MULTIPLIER_BONUS
# TOUGHNESS
# LIGHT_ARMOR_FLAT_IGNORED
# LIGHT_ARMOR_FRACTION_IGNORED
# HEAVY_ARMOR_FLAT_IGNORED
# HEAVY_ARMOR_FRACTION_IGNORED
# ARMOR_FLAT_IGNORED
# ARMOR_FRACTION_IGNORED

# HEALTH_BONUS
# HEALTH_MULTIPLIER_BONUS
# MOVEMENT_SPEED_BONUS
# KNOCKBACK_RESISTANCE
# TOUGHNESS_BONUS
# ATTACK_DAMAGE_BONUS
# ATTACK_SPEED_BONUS
# LUCK_BONUS
# BLOCK_REACH
# STEP_HEIGHT
# SCALE
# GRAVITY
# SAFE_FALLING_DISTANCE
# FALL_DAMAGE_MULTIPLIER

# DAMAGE_DEALT
# MELEE_DAMAGE_DEALT
# RANGED_DAMAGE_DEALT
# UNARMED_DAMAGE_DEALT
# VELOCITY_DAMAGE_BONUS
# LIGHT_ARMOR_DAMAGE_BONUS
# HEAVY_ARMOR_DAMAGE_BONUS
# FIRE_DAMAGE_BONUS
# EXPLOSION_DAMAGE_BONUS
# POISON_DAMAGE_BONUS
# MAGIC_DAMAGE_BONUS
# LIGHTNING_DAMAGE_BONUS
# FREEZING_DAMAGE_BONUS
# RADIANT_DAMAGE_BONUS
# NECROTIC_DAMAGE_BONUS
# BLUDGEONING_DAMAGE_BONUS
# FIRE_DAMAGE_DEALT
# EXPLOSION_DAMAGE_DEALT
# POISON_DAMAGE_DEALT
# BLUDGEONING_DAMAGE_DEALT
# MAGIC_DAMAGE_DEALT
# LIGHTNING_DAMAGE_DEALT
# FREEZING_DAMAGE_DEALT
# RADIANT_DAMAGE_DEALT
# NECROTIC_DAMAGE_DEALT

# POWER_ATTACK_DAMAGE_MULTIPLIER
# POWER_ATTACK_RADIUS
# POWER_ATTACK_DAMAGE_FRACTION
# ATTACK_REACH_BONUS
# ATTACK_REACH_MULTIPLIER
# RANGED_INACCURACY
# RANGED_VELOCITY_BONUS
# KNOCKBACK_BONUS
# IMMUNITY_FRAME_BONUS
# IMMUNITY_FRAME_MULTIPLIER
# BLEED_CHANCE
# BLEED_DAMAGE
# BLEED_DURATION
# DODGE_CHANCE
# REFLECT_CHANCE
# REFLECT_FRACTION
# DISMOUNT_CHANCE
# STUN_CHANCE
# STUN_DURATION_BONUS
# CRIT_CHANCE
# CRIT_DAMAGE
# CROSSBOW_MAGAZINE

# PARRY_EFFECTIVENESS_DURATION
# PARRY_VULNERABLE_DURATION
# PARRY_ENEMY_DEBUFF_DURATION
# PARRY_SELF_DEBUFF_DURATION
# PARRY_DAMAGE_REDUCTION
# PARRY_COOLDOWN
# PARRY_SUCCESS_COOLDOWN_REDUCTION

# DAMAGE_RESISTANCE
# MELEE_RESISTANCE
# PROJECTILE_RESISTANCE
# BLUDGEONING_RESISTANCE
# FIRE_RESISTANCE
# EXPLOSION_RESISTANCE
# MAGIC_RESISTANCE
# POISON_RESISTANCE
# FREEZING_RESISTANCE
# LIGHTNING_RESISTANCE
# RADIANT_RESISTANCE
# NECROTIC_RESISTANCE
# FALLING_RESISTANCE
# STUN_RESISTANCE
# BLEED_RESISTANCE
# CRIT_CHANCE_RESISTANCE
# CRIT_DAMAGE_RESISTANCE

# HEALING_BONUS
# HUNGER_SAVE_CHANCE
# COOLDOWN_REDUCTION
# CRAFTING_TIME_REDUCTION
# COOKING_SPEED_BONUS
# AMMO_SAVE_CHANCE
# DURABILITY_BONUS
# ENTITY_DROPS
# ENTITY_DROP_LUCK
# JUMP_HEIGHT_MULTIPLIER
# JUMPS_BONUS
# SNEAK_MOVEMENT_SPEED_BONUS
# SPRINT_MOVEMENT_SPEED_BONUS
# DIG_SPEED
# BLOCK_SPECIFIC_DIG_SPEED
# FISHING_LUCK
# FISHING_SPEED_MULTIPLIER
# EXPLOSION_RADIUS_MULTIPLIER

# FOOD_BONUS_VEGETABLE
# FOOD_BONUS_SEASONING
# FOOD_BONUS_ALCOHOLIC
# FOOD_BONUS_BEVERAGE
# FOOD_BONUS_SPOILED
# FOOD_BONUS_SEAFOOD
# FOOD_BONUS_MAGICAL
# FOOD_BONUS_SWEET
# FOOD_BONUS_GRAIN
# FOOD_BONUS_FRUIT
# FOOD_BONUS_NUTS
# FOOD_BONUS_DAIRY
# FOOD_BONUS_MEAT
# FOOD_BONUS_FATS

# SMITHING_QUALITY_GENERAL
# SMITHING_QUALITY_WOOD
# SMITHING_QUALITY_LEATHER
# SMITHING_QUALITY_STONE
# SMITHING_QUALITY_CHAINMAIL
# SMITHING_QUALITY_GOLD
# SMITHING_QUALITY_IRON
# SMITHING_QUALITY_DIAMOND
# SMITHING_QUALITY_NETHERITE
# SMITHING_QUALITY_BOW
# SMITHING_QUALITY_CROSSBOW
# SMITHING_QUALITY_PRISMARINE
# SMITHING_QUALITY_ENDERIC
# SMITHING_FRACTION_QUALITY_GENERAL
# SMITHING_FRACTION_QUALITY_WOOD
# SMITHING_FRACTION_QUALITY_LEATHER
# SMITHING_FRACTION_QUALITY_STONE
# SMITHING_FRACTION_QUALITY_CHAINMAIL
# SMITHING_FRACTION_QUALITY_GOLD
# SMITHING_FRACTION_QUALITY_IRON
# SMITHING_FRACTION_QUALITY_DIAMOND
# SMITHING_FRACTION_QUALITY_NETHERITE
# SMITHING_FRACTION_QUALITY_BOW
# SMITHING_FRACTION_QUALITY_CROSSBOW
# SMITHING_FRACTION_QUALITY_PRISMARINE
# SMITHING_FRACTION_QUALITY_ENDERIC
# SMITHING_EXP_GAIN_GENERAL
# SMITHING_EXP_GAIN_WOOD
# SMITHING_EXP_GAIN_LEATHER
# SMITHING_EXP_GAIN_STONE
# SMITHING_EXP_GAIN_CHAINMAIL
# SMITHING_EXP_GAIN_GOLD
# SMITHING_EXP_GAIN_IRON
# SMITHING_EXP_GAIN_DIAMOND
# SMITHING_EXP_GAIN_NETHERITE
# SMITHING_EXP_GAIN_BOW
# SMITHING_EXP_GAIN_CROSSBOW
# SMITHING_EXP_GAIN_PRISMARINE
# SMITHING_EXP_GAIN_ENDERIC

# ALCHEMY_QUALITY_GENERAL
# ALCHEMY_QUALITY_DEBUFF
# ALCHEMY_QUALITY_BUFF
# ALCHEMY_FRACTION_QUALITY_GENERAL
# ALCHEMY_FRACTION_QUALITY_DEBUFF
# ALCHEMY_FRACTION_QUALITY_BUFF
# BREWING_SPEED_BONUS
# BREWING_INGREDIENT_SAVE_CHANCE
# POTION_SAVE_CHANCE
# THROW_VELOCITY_BONUS
# ALCHEMY_EXP_GAIN
# SPLASH_INTENSITY_MINIMUM
# LINGERING_DURATION_MULTIPLIER
# LINGERING_RADIUS_MULTIPLIER

# ENCHANTING_QUALITY
# ENCHANTING_FRACTION_QUALITY
# ENCHANTING_QUALITY_ANVIL
# ENCHANTING_FRACTION_QUALITY_ANVIL
# ENCHANTING_AMPLIFY_CHANCE
# ENCHANTING_LAPIS_SAVE_CHANCE
# ENCHANTING_VANILLA_EXP_GAIN
# ENCHANTING_REFUND_CHANCE
# ENCHANTING_REFUND_AMOUNT
# ENCHANTING_EXP_GAIN

# BUTCHERY_DROP_MULTIPLIER
# FARMING_DROP_MULTIPLIER
# FARMING_LUCK
# FARMING_EXP_GAIN

# MINING_DROP_MULTIPLIER
# MINING_LUCK
# BLASTING_DROP_MULTIPLIER
# BLASTING_LUCK
# MINING_EXP_GAIN

# DIGGING_DROP_MULTIPLIER
# DIGGING_LUCK
# DIGGING_ARCHAEOLOGY_LUCK
# DIGGING_EXP_GAIN

# WOODCUTTING_DROP_MULTIPLIER
# WOODCUTTING_LUCK
# WOODCUTTING_EXP_GAIN

# FISHING_EXP_GAIN

# ARCHERY_EXP_GAIN

# LIGHT_ARMOR_EXP_GAIN

# HEAVY_ARMOR_EXP_GAIN

# LIGHT_WEAPONS_EXP_GAIN

# HEAVY_WEAPONS_EXP_GAIN